/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "input/router.v:1" *)
module top(\dest_x[0] , \dest_x[1] , \dest_x[2] , \dest_x[3] , \dest_x[4] , \dest_x[5] , \dest_x[6] , \dest_x[7] , \dest_x[8] , \dest_x[9] , \dest_x[10] , \dest_x[11] , \dest_x[12] , \dest_x[13] , \dest_x[14] , \dest_x[15] , \dest_x[16] , \dest_x[17] , \dest_x[18] , \dest_x[19] , \dest_x[20] , \dest_x[21] , \dest_x[22] , \dest_x[23] , \dest_x[24] , \dest_x[25] , \dest_x[26] , \dest_x[27] , \dest_x[28] , \dest_x[29] , \dest_y[0] , \dest_y[1] , \dest_y[2] , \dest_y[3] , \dest_y[4] , \dest_y[5] , \dest_y[6] , \dest_y[7] , \dest_y[8] , \dest_y[9] , \dest_y[10] , \dest_y[11] , \dest_y[12] , \dest_y[13] , \dest_y[14] , \dest_y[15] , \dest_y[16] , \dest_y[17] , \dest_y[18] , \dest_y[19] , \dest_y[20] , \dest_y[21] , \dest_y[22] , \dest_y[23] , \dest_y[24] , \dest_y[25] , \dest_y[26] , \dest_y[27] , \dest_y[28] , \dest_y[29] , \outport[0] , \outport[1] , \outport[2] , \outport[3] , \outport[4] , \outport[5] , \outport[6] , \outport[7] , \outport[8] , \outport[9] , \outport[10] , \outport[11] , \outport[12] , \outport[13] , \outport[14] , \outport[15] , \outport[16] , \outport[17] , \outport[18] , \outport[19] , \outport[20] , \outport[21] , \outport[22] , \outport[23] , \outport[24] , \outport[25] , \outport[26] , \outport[27] , \outport[28] , \outport[29] );
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  (* src = "input/router.v:21" *)
  input \dest_x[0] ;
  (* src = "input/router.v:21" *)
  input \dest_x[10] ;
  (* src = "input/router.v:21" *)
  input \dest_x[11] ;
  (* src = "input/router.v:21" *)
  input \dest_x[12] ;
  (* src = "input/router.v:21" *)
  input \dest_x[13] ;
  (* src = "input/router.v:21" *)
  input \dest_x[14] ;
  (* src = "input/router.v:21" *)
  input \dest_x[15] ;
  (* src = "input/router.v:21" *)
  input \dest_x[16] ;
  (* src = "input/router.v:21" *)
  input \dest_x[17] ;
  (* src = "input/router.v:21" *)
  input \dest_x[18] ;
  (* src = "input/router.v:21" *)
  input \dest_x[19] ;
  (* src = "input/router.v:21" *)
  input \dest_x[1] ;
  (* src = "input/router.v:21" *)
  input \dest_x[20] ;
  (* src = "input/router.v:21" *)
  input \dest_x[21] ;
  (* src = "input/router.v:21" *)
  input \dest_x[22] ;
  (* src = "input/router.v:21" *)
  input \dest_x[23] ;
  (* src = "input/router.v:21" *)
  input \dest_x[24] ;
  (* src = "input/router.v:21" *)
  input \dest_x[25] ;
  (* src = "input/router.v:21" *)
  input \dest_x[26] ;
  (* src = "input/router.v:21" *)
  input \dest_x[27] ;
  (* src = "input/router.v:21" *)
  input \dest_x[28] ;
  (* src = "input/router.v:21" *)
  input \dest_x[29] ;
  (* src = "input/router.v:21" *)
  input \dest_x[2] ;
  (* src = "input/router.v:21" *)
  input \dest_x[3] ;
  (* src = "input/router.v:21" *)
  input \dest_x[4] ;
  (* src = "input/router.v:21" *)
  input \dest_x[5] ;
  (* src = "input/router.v:21" *)
  input \dest_x[6] ;
  (* src = "input/router.v:21" *)
  input \dest_x[7] ;
  (* src = "input/router.v:21" *)
  input \dest_x[8] ;
  (* src = "input/router.v:21" *)
  input \dest_x[9] ;
  (* src = "input/router.v:21" *)
  input \dest_y[0] ;
  (* src = "input/router.v:21" *)
  input \dest_y[10] ;
  (* src = "input/router.v:21" *)
  input \dest_y[11] ;
  (* src = "input/router.v:21" *)
  input \dest_y[12] ;
  (* src = "input/router.v:21" *)
  input \dest_y[13] ;
  (* src = "input/router.v:21" *)
  input \dest_y[14] ;
  (* src = "input/router.v:21" *)
  input \dest_y[15] ;
  (* src = "input/router.v:21" *)
  input \dest_y[16] ;
  (* src = "input/router.v:21" *)
  input \dest_y[17] ;
  (* src = "input/router.v:21" *)
  input \dest_y[18] ;
  (* src = "input/router.v:21" *)
  input \dest_y[19] ;
  (* src = "input/router.v:21" *)
  input \dest_y[1] ;
  (* src = "input/router.v:21" *)
  input \dest_y[20] ;
  (* src = "input/router.v:21" *)
  input \dest_y[21] ;
  (* src = "input/router.v:21" *)
  input \dest_y[22] ;
  (* src = "input/router.v:21" *)
  input \dest_y[23] ;
  (* src = "input/router.v:21" *)
  input \dest_y[24] ;
  (* src = "input/router.v:21" *)
  input \dest_y[25] ;
  (* src = "input/router.v:21" *)
  input \dest_y[26] ;
  (* src = "input/router.v:21" *)
  input \dest_y[27] ;
  (* src = "input/router.v:21" *)
  input \dest_y[28] ;
  (* src = "input/router.v:21" *)
  input \dest_y[29] ;
  (* src = "input/router.v:21" *)
  input \dest_y[2] ;
  (* src = "input/router.v:21" *)
  input \dest_y[3] ;
  (* src = "input/router.v:21" *)
  input \dest_y[4] ;
  (* src = "input/router.v:21" *)
  input \dest_y[5] ;
  (* src = "input/router.v:21" *)
  input \dest_y[6] ;
  (* src = "input/router.v:21" *)
  input \dest_y[7] ;
  (* src = "input/router.v:21" *)
  input \dest_y[8] ;
  (* src = "input/router.v:21" *)
  input \dest_y[9] ;
  (* src = "input/router.v:33" *)
  output \outport[0] ;
  (* src = "input/router.v:33" *)
  output \outport[10] ;
  (* src = "input/router.v:33" *)
  output \outport[11] ;
  (* src = "input/router.v:33" *)
  output \outport[12] ;
  (* src = "input/router.v:33" *)
  output \outport[13] ;
  (* src = "input/router.v:33" *)
  output \outport[14] ;
  (* src = "input/router.v:33" *)
  output \outport[15] ;
  (* src = "input/router.v:33" *)
  output \outport[16] ;
  (* src = "input/router.v:33" *)
  output \outport[17] ;
  (* src = "input/router.v:33" *)
  output \outport[18] ;
  (* src = "input/router.v:33" *)
  output \outport[19] ;
  (* src = "input/router.v:33" *)
  output \outport[1] ;
  (* src = "input/router.v:33" *)
  output \outport[20] ;
  (* src = "input/router.v:33" *)
  output \outport[21] ;
  (* src = "input/router.v:33" *)
  output \outport[22] ;
  (* src = "input/router.v:33" *)
  output \outport[23] ;
  (* src = "input/router.v:33" *)
  output \outport[24] ;
  (* src = "input/router.v:33" *)
  output \outport[25] ;
  (* src = "input/router.v:33" *)
  output \outport[26] ;
  (* src = "input/router.v:33" *)
  output \outport[27] ;
  (* src = "input/router.v:33" *)
  output \outport[28] ;
  (* src = "input/router.v:33" *)
  output \outport[29] ;
  (* src = "input/router.v:33" *)
  output \outport[2] ;
  (* src = "input/router.v:33" *)
  output \outport[3] ;
  (* src = "input/router.v:33" *)
  output \outport[4] ;
  (* src = "input/router.v:33" *)
  output \outport[5] ;
  (* src = "input/router.v:33" *)
  output \outport[6] ;
  (* src = "input/router.v:33" *)
  output \outport[7] ;
  (* src = "input/router.v:33" *)
  output \outport[8] ;
  (* src = "input/router.v:33" *)
  output \outport[9] ;
  assign _146_ = ~\dest_x[24] ;
  assign _147_ = ~\dest_x[23] ;
  assign _148_ = ~\dest_x[17] ;
  assign _149_ = ~\dest_x[18] ;
  assign _150_ = ~\dest_x[16] ;
  assign _151_ = ~\dest_x[11] ;
  assign _152_ = ~(\dest_x[9]  | \dest_x[10] );
  assign _153_ = ~(\dest_x[13]  | \dest_x[12] );
  assign _154_ = ~((_152_ | _151_) & _153_);
  assign _155_ = _154_ & \dest_x[14] ;
  assign _156_ = ~(_155_ & \dest_x[15] );
  assign _157_ = _156_ & _150_;
  assign _158_ = ~((_157_ | _148_) & _149_);
  assign _159_ = \dest_x[20]  & \dest_x[19] ;
  assign _160_ = \dest_x[22]  | \dest_x[21] ;
  assign _161_ = ~((_159_ & _158_) | _160_);
  assign _162_ = _161_ | _147_;
  assign _163_ = ~(_162_ | _146_);
  assign _164_ = _163_ & \dest_x[25] ;
  assign _165_ = _164_ | \dest_x[26] ;
  assign _166_ = _165_ & \dest_x[27] ;
  assign _167_ = \dest_x[29]  & \dest_x[28] ;
  assign _168_ = _165_ | \dest_x[27] ;
  assign _169_ = _163_ | \dest_x[25] ;
  assign _170_ = ~_158_;
  assign _171_ = \dest_x[22]  & \dest_x[21] ;
  assign _172_ = ~(_171_ & _159_);
  assign _173_ = ~((_172_ | _170_) & _147_);
  assign _174_ = _155_ | \dest_x[15] ;
  assign _175_ = \dest_x[5]  & \dest_x[4] ;
  assign _176_ = \dest_x[3]  & \dest_x[2] ;
  assign _177_ = _176_ & _175_;
  assign _178_ = \dest_x[24]  & \dest_x[20] ;
  assign _179_ = ~\dest_x[26] ;
  assign _180_ = \dest_x[1]  & _179_;
  assign _181_ = _180_ & _178_;
  assign _000_ = _181_ & _177_;
  assign _001_ = \dest_x[7]  & \dest_x[6] ;
  assign _002_ = \dest_x[0]  & \dest_x[8] ;
  assign _003_ = ~(_002_ & _001_);
  assign _004_ = ~((_152_ & _151_) | _003_);
  assign _005_ = _004_ & _000_;
  assign _006_ = \dest_x[19]  & _149_;
  assign _007_ = \dest_x[17]  ^ \dest_x[16] ;
  assign _008_ = _007_ & _006_;
  assign _009_ = _150_ & \dest_x[14] ;
  assign _010_ = _009_ & _152_;
  assign _011_ = _167_ & _153_;
  assign _012_ = _011_ & _010_;
  assign _013_ = _012_ & _008_;
  assign _014_ = _013_ & _005_;
  assign _015_ = _014_ & _174_;
  assign _016_ = _015_ & _173_;
  assign _017_ = _016_ & _162_;
  assign _018_ = _017_ & _169_;
  assign _019_ = ~((_018_ & _168_) | (_167_ & _166_));
  assign _020_ = ~(_167_ & _166_);
  assign _021_ = _162_ & _146_;
  assign _022_ = \dest_x[25]  ? _163_ : _021_;
  assign _023_ = ~_157_;
  assign _024_ = \dest_x[15]  | \dest_x[14] ;
  assign _025_ = _024_ | _154_;
  assign _026_ = ~(_151_ | \dest_x[10] );
  assign _027_ = ~(_026_ & _153_);
  assign _028_ = ~_006_;
  assign _029_ = _028_ | _160_;
  assign _030_ = _029_ | _027_;
  assign _031_ = \dest_x[6]  | \dest_x[5] ;
  assign _032_ = \dest_x[8]  | \dest_x[7] ;
  assign _033_ = _032_ | _031_;
  assign _034_ = \dest_x[4]  | \dest_x[3] ;
  assign _035_ = \dest_x[2]  | \dest_x[1] ;
  assign _036_ = _035_ | _034_;
  assign _037_ = ~(\dest_x[20]  & \dest_x[17] );
  assign _038_ = ~(\dest_x[9]  & \dest_x[23] );
  assign _039_ = _038_ | _037_;
  assign _040_ = _039_ | _036_;
  assign _041_ = _040_ | _033_;
  assign _042_ = _041_ | _030_;
  assign _043_ = ~((_025_ & \dest_x[16] ) | _042_);
  assign _044_ = _043_ & _023_;
  assign _045_ = ~(_044_ & _022_);
  assign _046_ = ~((_164_ & \dest_x[26] ) | _045_);
  assign _047_ = ~(_046_ | _020_);
  assign \outport[0]  = _047_ | _019_;
  assign _048_ = ~\dest_y[27] ;
  assign _049_ = ~\dest_y[26] ;
  assign _050_ = ~\dest_y[24] ;
  assign _051_ = ~\dest_y[21] ;
  assign _052_ = ~\dest_y[13] ;
  assign _053_ = ~\dest_y[14] ;
  assign _054_ = ~\dest_y[12] ;
  assign _055_ = \dest_y[9]  | \dest_y[10] ;
  assign _056_ = ~(_055_ & \dest_y[11] );
  assign _057_ = _056_ & _054_;
  assign _058_ = ~((_057_ & _052_) | _053_);
  assign _059_ = \dest_y[18]  | \dest_y[16] ;
  assign _060_ = ~((_058_ & \dest_y[15] ) | _059_);
  assign _061_ = ~(\dest_y[20]  & \dest_y[19] );
  assign _062_ = ~_061_;
  assign _063_ = \dest_y[17]  | \dest_y[18] ;
  assign _064_ = _063_ & _062_;
  assign _065_ = ~_064_;
  assign _066_ = ~((_065_ | _060_) & _051_);
  assign _067_ = ~((_066_ | \dest_y[22] ) & \dest_y[23] );
  assign _068_ = ~(_067_ | _050_);
  assign _069_ = ~(_068_ & \dest_y[25] );
  assign _070_ = _069_ & _049_;
  assign _071_ = ~(_070_ | _048_);
  assign _072_ = _071_ & \dest_y[28] ;
  assign _073_ = ~(_072_ & \dest_y[29] );
  assign _074_ = ~(_071_ ^ \dest_y[28] );
  assign _075_ = _070_ ^ \dest_y[27] ;
  assign _076_ = _068_ & \dest_y[25] ;
  assign _077_ = _076_ ^ \dest_y[26] ;
  assign _078_ = ~(_065_ | _060_);
  assign _079_ = _078_ ^ \dest_y[21] ;
  assign _080_ = _066_ & \dest_y[22] ;
  assign _081_ = _062_ & _055_;
  assign _082_ = \dest_y[9]  & \dest_y[10] ;
  assign _083_ = ~(\dest_y[17]  & \dest_y[15] );
  assign _084_ = ~(_083_ | _082_);
  assign _085_ = _084_ & _081_;
  assign _086_ = ~\dest_y[1] ;
  assign _087_ = _086_ & \dest_y[9] ;
  assign _088_ = \dest_y[14]  & \dest_y[11] ;
  assign _089_ = _088_ & _087_;
  assign _090_ = \dest_y[13]  | \dest_y[12] ;
  assign _091_ = ~(_090_ | _059_);
  assign _092_ = _091_ & _089_;
  assign _093_ = \dest_y[7]  | \dest_y[6] ;
  assign _094_ = ~(_093_ | \dest_y[8] );
  assign _095_ = ~(\dest_y[3]  | \dest_y[2] );
  assign _096_ = ~(\dest_y[5]  | \dest_y[4] );
  assign _097_ = _096_ & _095_;
  assign _098_ = _097_ & _094_;
  assign _099_ = _098_ & _092_;
  assign _100_ = ~(_099_ & _085_);
  assign _101_ = ~(_100_ | _080_);
  assign _102_ = _101_ & _079_;
  assign _103_ = _102_ & _068_;
  assign _104_ = _103_ & _076_;
  assign _105_ = _104_ & _077_;
  assign _106_ = _105_ & _075_;
  assign _107_ = ~((_106_ & _074_) | _073_);
  assign _108_ = ~(\dest_y[0]  | \dest_x[0] );
  assign _109_ = ~(_066_ | \dest_y[22] );
  assign _110_ = ~((_109_ & \dest_y[23] ) | _080_);
  assign _111_ = _055_ & \dest_y[11] ;
  assign _112_ = \dest_y[13]  & \dest_y[12] ;
  assign _113_ = ~((_112_ & _111_) | \dest_y[14] );
  assign _114_ = \dest_y[8]  & \dest_y[7] ;
  assign _115_ = ~(_114_ & \dest_y[29] );
  assign _116_ = ~(_115_ | _111_);
  assign _117_ = ~((_082_ | \dest_y[11] ) & _116_);
  assign _118_ = ~(\dest_y[24]  & \dest_y[0] );
  assign _119_ = _118_ | _059_;
  assign _120_ = _083_ | _061_;
  assign _121_ = _120_ | _119_;
  assign _122_ = ~(\dest_y[4]  & \dest_y[3] );
  assign _123_ = ~(\dest_y[6]  & \dest_y[5] );
  assign _124_ = _123_ | _122_;
  assign _125_ = ~\dest_y[25] ;
  assign _126_ = \dest_y[9]  | _125_;
  assign _127_ = ~(\dest_y[2]  & \dest_y[1] );
  assign _128_ = _127_ | _126_;
  assign _129_ = _128_ | _124_;
  assign _130_ = _129_ | _121_;
  assign _131_ = _130_ | _117_;
  assign _132_ = _131_ | _058_;
  assign _133_ = _132_ | _113_;
  assign _134_ = ~(_133_ | _079_);
  assign _135_ = ~(_134_ & _067_);
  assign _136_ = _135_ | _110_;
  assign _137_ = _136_ | _077_;
  assign _138_ = _137_ | _075_;
  assign _139_ = ~((_138_ | _074_) & (_108_ | _073_));
  assign _140_ = _139_ | _107_;
  assign _141_ = ~((_073_ & \dest_x[0] ) | _019_);
  assign \outport[1]  = ~((_141_ & _140_) | _047_);
  assign _142_ = _106_ & _074_;
  assign _143_ = _142_ | _073_;
  assign _144_ = ~(\dest_y[0]  & \dest_x[0] );
  assign _145_ = _144_ | _073_;
  assign \outport[2]  = ~((_145_ & _143_) | \outport[0] );
  assign \outport[10]  = 1'b0;
  assign \outport[11]  = 1'b0;
  assign \outport[12]  = 1'b0;
  assign \outport[13]  = 1'b0;
  assign \outport[14]  = 1'b0;
  assign \outport[15]  = 1'b0;
  assign \outport[16]  = 1'b0;
  assign \outport[17]  = 1'b0;
  assign \outport[18]  = 1'b0;
  assign \outport[19]  = 1'b0;
  assign \outport[20]  = 1'b0;
  assign \outport[21]  = 1'b0;
  assign \outport[22]  = 1'b0;
  assign \outport[23]  = 1'b0;
  assign \outport[24]  = 1'b0;
  assign \outport[25]  = 1'b0;
  assign \outport[26]  = 1'b0;
  assign \outport[27]  = 1'b0;
  assign \outport[28]  = 1'b0;
  assign \outport[29]  = 1'b0;
  assign \outport[3]  = 1'b0;
  assign \outport[4]  = 1'b0;
  assign \outport[5]  = 1'b0;
  assign \outport[6]  = 1'b0;
  assign \outport[7]  = 1'b0;
  assign \outport[8]  = 1'b0;
  assign \outport[9]  = 1'b0;
endmodule
